name: cd

on:
  push:
    branches: [master]
  workflow_dispatch: 
     

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.4.2
        with:
           dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish ./ECommerceOrderAPI.UI/ECommerceOrderAPI.UI.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: api-artifact
          path: ${{ env.DOTNET_ROOT }}/a
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: api-artifact
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v3.0.1
        with:
          app-name: 'ECommerceOrderApp'
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          
